### ISSUE TITLE
Blank page when uploading .json report

### ISSUE THREAD

**Issue by MonikaSimkeviciene** [daisy/ace-smart#1] opened 2023-12-11 07:35 UTC
Hello, I am trying to upload my ace .json report in SMART, but whether I drag and drop or selecting file from folder, a blank page appears and nothing happens. Where is the problem and how to solve it?
![Screenshot 2023-12-11 093256](https://github.com/daisy/ace-smart/assets/153490150/dda034e1-8ae6-487b-aa75-9ab4646dbc5f)

**Comment by mattgarrish** [comment] 2023-12-11 14:15
The most likely cause is something in the json file is crashing the scripts on the page, but I haven't been able to reproduce the issue.

If you could send me the json file privately, that would help in figuring out the problem.

If you can't send it, from the screenshot it looks like you're using chrome or edge. If so, could you try pressing F12 to open the developer tools and then switch to the Console tab before loading the json report and then paste a screen shot of any errors that show up?

**Comment by mattgarrish** [comment] 2023-12-12 14:21
For the record, the issue was with the encoding of one of the database tables. It looks like a recent upgrade to the user management code changed it from unicode to a latin character set. Closing this issue as it's fixed now.

**Closed as completed by mattgarrish** 2023-12-12 14:21 UTC
